name: net_pro_fan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  carousel_slider: ^4.1.1
  dropdown_button2: ^1.7.2
  flutter_spinkit: ^5.1.0
  flutter_speed_dial: ^6.0.0
  url_launcher: ^6.1.5
  google_maps_flutter: ^2.1.12
  bot_toast: ^4.0.3
  flutter_advanced_drawer: ^1.3.2

  # Fetch server data & State management :
  provider: ^6.0.3
  http: ^0.13.5
  connectivity_plus: ^2.3.6+1

  # Image View :
  flutter_svg: ^1.1.4
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0

#  file_picker: ^0.8.5+3
  file_picker: ^4.5.1
  open_file: ^3.2.1

  # Localizations :
  intl: ^0.17.0

  # Local Database :
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  sqflite: ^2.0.3+1

  # Firebase Database :
  firebase_core: ^1.21.1
  firebase_crashlytics: ^2.8.9
  firebase_analytics: ^9.3.3
  package_info_plus: ^1.4.2
  firebase_remote_config: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/image/
    - asset/icon/


  fonts:
    - family: Quicksand
      fonts:
        - asset: asset/font/quicksand/Quicksand-Light.ttf
          weight: 100
        - asset: asset/font/quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: asset/font/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: asset/font/quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: asset/font/quicksand/Quicksand-Bold.ttf
          weight: 700


flutter_intl:
  main_locale: en_US
  enabled: true
